
server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url: http://localhost:9091
  thymeleaf:
    prefix:
      classpath: /templates
    cache: false
info:
  version=@project:
    version@:

management:
    endpoints:
      web:
        exposure:
          include: '*'
    health:
      show-details: always